import { useState, useRef } from 'react';
const AddCar = () => {}
// MARQUE ET MODELE EN LISTE DEROULANTE OK

// KILOMETRAGE ET PUISSANCE FISCALE =/= SAISIE DE VALEUR

//TYPE DE CARBURANT = PLUSIEUR BOUTON DISPONIBLE ON PEUT EN CHOISIR 1 (FAIRE DISPARAITRE LES AUTRES ? OU JUSTE STYLISER ?)

//BOITE DE VITESSE ON PEUT EN CHOISIR 1 (FAIRE DISPARAITRE LES AUTRES ? OU JUSTE STYLISER ?)

//ETAT IDEM

//ORIGINE IDEM

//NOMBRE DE PORTES IDEM

//PREMIERE MAIN IDEM

//=================INFO ANNONCE====================//

//PRIX EN SAISIE DE VALEUR (CHOISIR DEVISE AVEC CONVERSION ?)

//TITRE DE L'ANNONCE

//DESCRIPTION

//PLUS DE DETAILS SELECTION MULTIPLE DE BOUTONS






export default AddCar;